target 'AXCGiphy', :exclusive => true do
  pod "Giphy-iOS", :path => "../"
  pod 'AFNetworking/Serialization', '~> 3.1.0'
  pod 'AnimatedGIFImageSerialization', '~> 0.2.0'
end

target 'Tests', :exclusive => true do
  pod "Giphy-iOS", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
